# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190405_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Teacher', verbose_name='课程讲师'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='teacherassistant',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Teacher', verbose_name='讲师'),
        ),
    ]
